server:
  port: 9090

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/enamul-java/config-server
          clone-on-start: true