#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/user_service
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      jdbc:
#        lob:
#          non_contextual_creation: 'true'
#      ddl-auto: create-drop
#    show-sql: 'true'
server:
  port: '8089'